NickLindeberg/black_thursday

- Gemfile.lock
- lib/.gitignore
- lib/merchant.rb
- test/.gitignore
- test/merchant_test.rb
Adds merchant class with attributes and test
> adds merchant class with attributes and test

- Rakefile
- lib/item.rb
- lib/merchant.rb
- test/item_test.rb
- test/merchant_test.rb
Adds item class with methods and tests for attributes and unit_price_To_dollar
> Add item class

- lib/item.rb
- lib/merchant.rb
- lib/merchant_repository.rb
- test/item_test.rb
- test/merchant_repository_test.rb
- test/merchant_test.rb
Setups up Tests and Class for Merchant Repository
> Initial merchantrepo setup

- lib/item_repository.rb
- test/item_repository_test.rb
- test/merchant_repository_test.rb
Adds item_repo class and tests.
> creates item_repository class and test

- lib/merchant_repository.rb
- lib/sales_engine.rb
- test/merchant_repository_test.rb
- test/merchant_test.rb
- test/sales_engine_test.rb
Adds SalesEngine class with tests. Methods to create ItemRepository and MerchantRepository.
> Sales engine setup

- lib/merchant.rb
- lib/merchant_repository.rb
- test/merchant_repository_test.rb
- test/merchant_test.rb
> Build merchant repo

- test/item_repository_test.rb
- test/item_test.rb
- test/merchant_repository_test.rb
- test/merchant_test.rb
- test/sales_engine_test.rb
- test/test_helper.rb
Moves the minitest require statements into test_helper and adds simplecov
> Condenses tests for test_helper

- lib/item.rb
- lib/item_repository.rb
- lib/sales_engine.rb
- test/item_repository_test.rb
- test/merchant_repository_test.rb
- test/sales_engine_test.rb
Adds methods and tests for Item Repository
> Builds item repo

- lib/sales_engine.rb
> updates sales engine, in progress

- lib/item.rb
- lib/item_repository.rb
- lib/merchant_repository.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- test/item_repository_test.rb
- test/sales_engine_test.rb
Updates methods within item repo.  In progress.
> Sales engine test

- lib/item.rb
- lib/item_repository.rb
Adds fixes for BigDecimal data types in item and item_repository classes.
> Big decimal updates

- lib/item.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
- test/sales_analyst_test.rb
Adds methods and tests for golden items
> Sales analyst updates

- lib/merchant_repository.rb
- test/merchant_repository_test.rb
Switches merchant test information
> Updates merchant_repo test

- lib/invoice.rb
- test/invoice_test.rb
Creates invoice class and test files.
> Build invoice class

- lib/invoice.rb
- lib/invoice_repository.rb
- lib/item_repository.rb
- lib/merchant_repository.rb
- lib/repository.rb
- lib/sales_engine.rb
- test/invoice_repository_test.rb
- test/sales_engine_test.rb
Updates sales engine class and test.  In progress
> Invoice repo additions

- lib/item_repository.rb
- lib/sales_analyst.rb
- lib/sales_engine.rb
Fixes instance variable in SalesEngine, adds argument to SalesAnalyst
> Minor fixes to sales_engine to fix invoices

- lib/invoice.rb
- lib/sales_analyst.rb
- test/invoice_repository_test.rb
- test/invoice_test.rb
- test/sales_analyst_test.rb
Adds invoices methods to sales analyst.  In progress
> Add invoice function sa

- lib/sales_analyst.rb
- test/sales_analyst_test.rb
Finishes all methods for Iteration 2.
> Finish invoice function sa

- lib/invoice_item.rb
- lib/item.rb
- test/invoice_item_test.rb
Adds class and test files for invoice_item class
> Create invoice item class

- lib/invoice_item_repository.rb
- test/invoice_item_repository_test.rb
Creates class and test files for invoice_item_repository class.
> Starts invoice_item_repository.rb

- lib/transaction.rb
- test/transaction_test.rb
Adds test and class file for transaction class
> Builds transaction class

- lib/invoice_item.rb
- lib/invoice_item_repository.rb
- lib/repository.rb
- lib/sales_engine.rb
- test/invoice_item_repository_test.rb
Adds more methods to InvoiceItemRepository Class
> Invoice item repository

- lib/customer.rb
- lib/customer_repository.rb
- lib/sales_engine.rb
- test/customer_repository_test.rb
Builds out methods in customer repository and creates tests
> Creates customer repository

- lib/sales_engine.rb
- lib/transaction.rb
- lib/transaction_repository.rb
- test/transaction_repository_test.rb
Builds Transactions repository with test file and updates sales engine.
> Builds transaction repository

- lib/transaction.rb
- lib/transaction_repository.rb
- test/transaction_repository_test.rb
- test/transaction_test.rb
Updates method and test for transaction for "find by result" method.
> Transaction updates

- lib/sales_analyst.rb
- lib/sales_engine.rb
- test/sales_analyst_test.rb
- test/sales_engine_test.rb
Adds transaction, invoice_items, and customer repositories and information to sales_engine
> Updates sales engine test

- lib/sales_analyst.rb
- test/sales_analyst_test.rb
Adds final methods and tests to sales analyst
> Revenue methods

- test/item_repository_test.rb
- test/merchant_test.rb
- test/sales_analyst_test.rb
Updates test coverage for simple cov.
> Test coverage
